### PR TITLE
Fixes yarn.lock for yarn check verification

### PR DESCRIPTION
**Pull request by tonycoco**
`yarn.lock` failed to pass `yarn check`. This fixes it without direct dependency modifications.

### CODE REVIEW

**Comment by nene** [comment]
Thanks for the PR.

Would you care to explain how did you achieve this? That is, I guess you didn't go through all the warnings one-by-one to resolve them, but did it in some automated way.

I'm also not sure what you mean by "without dependency modifications". Your PR definitely contains lots of changes to the dependencies listed in `yarn.lock` file.

**Comment by tonycoco** [comment]
Ahh yes, sorry, meant to say no direct dependencies changed. Underlying deps that were removed, outdated, or had critical fixes were changed so that `yarn check` works again. I did it by re-generating a `yarn.lock` file. I noticed the errors since a few projects I work on used `sql-formatter` as a [pre-commit](http://pre-commit.com) hook.

**Comment by nene** [comment]
Thanks for the explanation. Much appreciated!

**Comment by nene** [comment]
No problem. Done.

**Pull request merged**
