### PR TITLE
Nearley integration

### PR DESCRIPTION
**Pull request by nene**
That's an initial attempt at replacing our current parser with Nearley. Just trying it out and seeing what kind of problems arise.

Discovered several problems:

- [x] Case-sensitivity: Nearley matches against `token.text` field, which in our case (and in Moo) is the original text in source file. We should change it around, so that `token.text` would be the canonical/clean value to match against while some other field would store the original string.
- [x] Semicolons: Currently semicolon is just another operator, should turn it into a separate token type, which would simplify distinguishing it from other operators.
- [x] Ambiguity: our current parser simply goes with first rule that matches, while Nearley tries to match all possible rules, leading to ambiguity.

The first two are simple to fix, but the ambiquity problem is a major one.

For example I'd like to parse both function calls and plain blocks of parenthesis. If I write a grammar like this:

```
main -> expression:*

expression -> function_call | parenthesis | plain_token

function_call -> %IDENT parenthesis

parenthesis -> "(" expression:* ")"

plain_token -> %IDENT | %NUMBER | %STRING | %OPERATOR
```

and try to parse a string `foo()`, then Nearley will return two parse results:

- a `function_call`
- a `plain_token` followed by `parenthesis`

To solve this problem we would need to write a more complex grammar that only allows `IDENT` followed by `(` inside a function call.

### CODE REVIEW

**Comment by nene** [comment]
Finally replaced our old parser with Nearley-based parser.

All tests are passing, except for one which will get fixed by merging #400

Some general thoughts about the Nearley-based parser v/s our current one:

- The grammar.ne file (221 lines) is about the same size as our current manually written Parser.ts (212 lines).
- There are gotchas when writing it either manually or using Nearley syntax.
- Nearly will more likely throw an error to your face when you don't get your grammar right, while the manual parser will more likely so something silently wrong - so you'll more likely end up with incorrectly formatted code for unclear reasons, while with Nearley you more likely end up with an error message and no formatting happening at all.
- We no more support obviously broken syntax like `SELECT (` - no closing parenthesis.
- There are currently some hacks involved to distinguish between `func_name(...)` and separate `func_name` or `(...)`. Same with square brackets. The way to avoid these hacks would be to write a full grammar which is... yeah... a huge task. Luckily these hacks are at least neatly separated in [disambiguateTokens.ts](https://github.com/sql-formatter-org/sql-formatter/pull/277/files#diff-1394b10d3217cd106eb43113706acbf6a2b115253a93ab22a65408f6a9474683) file.
- In general though, I think using Nearley is a better approach overall. It won't quickly solve all our problems, but it's more likely a better foundation for moving forward.

I've marked this PR as ready for review, though there are still some tasks to do:

- [ ] Removal of the old Parser implementation.
- [ ] Performance measurements and optimizations (if needed).

**Comment by inferrinizzard** [comment]
Would like to propose moving the grammar.me back to its own grammar dir to serve as a base point for when we expand the grammar / split the singular ne file into multiple component files and have the parser dir only for parser typescript files

**Comment by nene** [comment]
> Would like to propose moving the grammar.me back to its own grammar dir

I think this can always be done later when the need arises. I don't see it as a certainty that we would split it up. Having looked at various other grammars in other projects, they always seem to be in a single file. We might end up needing multiple grammars for multiple sql dialects, but I wouldn't bet on it either.

**Comment by nene** [comment]
Ran the initial performance test with [jsben.ch](https://jsben.ch/), using my good old code:

```js
sqlFormatter.format(
  "select supplier_name,city from (select * from suppliers join addresses on suppliers.address_id=addresses.id) as suppliers where supplier_id>500 order by supplier_name asc,city desc; ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION; CREATE TABLE `Customer` ( `CustomerId` INT NOT NULL AUTO_INCREMENT, `FirstName` NVARCHAR(40) NOT NULL, `LastName` NVARCHAR(20) NOT NULL, `Company` NVARCHAR(80), `Address` NVARCHAR(70), `City` NVARCHAR(40), `State` NVARCHAR(40), `Country` NVARCHAR(40), `PostalCode` NVARCHAR(10), `Phone` NVARCHAR(24), `Fax` NVARCHAR(24), `Email` NVARCHAR(60) NOT NULL, `SupportRepId` INT, CONSTRAINT `PK_Customer` PRIMARY KEY  (`CustomerId`)); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Jump Around', 258, 1, 17, N'E. Schrody/L. Muggerud', 217835, 8715653, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Salutations', 258, 1, 17, N'E. Schrody/L. Dimant', 69120, 2767047, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Put Your Head Out', 258, 1, 17, N'E. Schrody/L. Freese/L. Muggerud', 182230, 7291473, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Top O'' The Morning To Ya', 258, 1, 17, N'E. Schrody/L. Dimant', 216633, 8667599, 0.99); INSERT INTO `Invoice` (`CustomerId`, `InvoiceDate`, `BillingAddress`, `BillingCity`, `BillingState`, `BillingCountry`, `BillingPostalCode`, `Total`) VALUES (48, '2013/8/2', N'Lijnbaansgracht 120bg', N'Amsterdam', N'VV', N'Netherlands', N'1016', 1.98);"
  + "select supplier_name,city from (select * from suppliers join addresses on suppliers.address_id=addresses.id) as suppliers where supplier_id>500 order by supplier_name asc,city desc; ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION; CREATE TABLE `Customer` ( `CustomerId` INT NOT NULL AUTO_INCREMENT, `FirstName` NVARCHAR(40) NOT NULL, `LastName` NVARCHAR(20) NOT NULL, `Company` NVARCHAR(80), `Address` NVARCHAR(70), `City` NVARCHAR(40), `State` NVARCHAR(40), `Country` NVARCHAR(40), `PostalCode` NVARCHAR(10), `Phone` NVARCHAR(24), `Fax` NVARCHAR(24), `Email` NVARCHAR(60) NOT NULL, `SupportRepId` INT, CONSTRAINT `PK_Customer` PRIMARY KEY  (`CustomerId`)); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Jump Around', 258, 1, 17, N'E. Schrody/L. Muggerud', 217835, 8715653, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Salutations', 258, 1, 17, N'E. Schrody/L. Dimant', 69120, 2767047, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Put Your Head Out', 258, 1, 17, N'E. Schrody/L. Freese/L. Muggerud', 182230, 7291473, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Top O'' The Morning To Ya', 258, 1, 17, N'E. Schrody/L. Dimant', 216633, 8667599, 0.99); INSERT INTO `Invoice` (`CustomerId`, `InvoiceDate`, `BillingAddress`, `BillingCity`, `BillingState`, `BillingCountry`, `BillingPostalCode`, `Total`) VALUES (48, '2013/8/2', N'Lijnbaansgracht 120bg', N'Amsterdam', N'VV', N'Netherlands', N'1016', 1.98);"
  + "select supplier_name,city from (select * from suppliers join addresses on suppliers.address_id=addresses.id) as suppliers where supplier_id>500 order by supplier_name asc,city desc; ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION; CREATE TABLE `Customer` ( `CustomerId` INT NOT NULL AUTO_INCREMENT, `FirstName` NVARCHAR(40) NOT NULL, `LastName` NVARCHAR(20) NOT NULL, `Company` NVARCHAR(80), `Address` NVARCHAR(70), `City` NVARCHAR(40), `State` NVARCHAR(40), `Country` NVARCHAR(40), `PostalCode` NVARCHAR(10), `Phone` NVARCHAR(24), `Fax` NVARCHAR(24), `Email` NVARCHAR(60) NOT NULL, `SupportRepId` INT, CONSTRAINT `PK_Customer` PRIMARY KEY  (`CustomerId`)); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Jump Around', 258, 1, 17, N'E. Schrody/L. Muggerud', 217835, 8715653, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Salutations', 258, 1, 17, N'E. Schrody/L. Dimant', 69120, 2767047, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Put Your Head Out', 258, 1, 17, N'E. Schrody/L. Freese/L. Muggerud', 182230, 7291473, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Top O'' The Morning To Ya', 258, 1, 17, N'E. Schrody/L. Dimant', 216633, 8667599, 0.99); INSERT INTO `Invoice` (`CustomerId`, `InvoiceDate`, `BillingAddress`, `BillingCity`, `BillingState`, `BillingCountry`, `BillingPostalCode`, `Total`) VALUES (48, '2013/8/2', N'Lijnbaansgracht 120bg', N'Amsterdam', N'VV', N'Netherlands', N'1016', 1.98);"
  + "select supplier_name,city from (select * from suppliers join addresses on suppliers.address_id=addresses.id) as suppliers where supplier_id>500 order by supplier_name asc,city desc; ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION; CREATE TABLE `Customer` ( `CustomerId` INT NOT NULL AUTO_INCREMENT, `FirstName` NVARCHAR(40) NOT NULL, `LastName` NVARCHAR(20) NOT NULL, `Company` NVARCHAR(80), `Address` NVARCHAR(70), `City` NVARCHAR(40), `State` NVARCHAR(40), `Country` NVARCHAR(40), `PostalCode` NVARCHAR(10), `Phone` NVARCHAR(24), `Fax` NVARCHAR(24), `Email` NVARCHAR(60) NOT NULL, `SupportRepId` INT, CONSTRAINT `PK_Customer` PRIMARY KEY  (`CustomerId`)); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Jump Around', 258, 1, 17, N'E. Schrody/L. Muggerud', 217835, 8715653, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Salutations', 258, 1, 17, N'E. Schrody/L. Dimant', 69120, 2767047, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Put Your Head Out', 258, 1, 17, N'E. Schrody/L. Freese/L. Muggerud', 182230, 7291473, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Top O'' The Morning To Ya', 258, 1, 17, N'E. Schrody/L. Dimant', 216633, 8667599, 0.99); INSERT INTO `Invoice` (`CustomerId`, `InvoiceDate`, `BillingAddress`, `BillingCity`, `BillingState`, `BillingCountry`, `BillingPostalCode`, `Total`) VALUES (48, '2013/8/2', N'Lijnbaansgracht 120bg', N'Amsterdam', N'VV', N'Netherlands', N'1016', 1.98);"
  + "select supplier_name,city from (select * from suppliers join addresses on suppliers.address_id=addresses.id) as suppliers where supplier_id>500 order by supplier_name asc,city desc; ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION; CREATE TABLE `Customer` ( `CustomerId` INT NOT NULL AUTO_INCREMENT, `FirstName` NVARCHAR(40) NOT NULL, `LastName` NVARCHAR(20) NOT NULL, `Company` NVARCHAR(80), `Address` NVARCHAR(70), `City` NVARCHAR(40), `State` NVARCHAR(40), `Country` NVARCHAR(40), `PostalCode` NVARCHAR(10), `Phone` NVARCHAR(24), `Fax` NVARCHAR(24), `Email` NVARCHAR(60) NOT NULL, `SupportRepId` INT, CONSTRAINT `PK_Customer` PRIMARY KEY  (`CustomerId`)); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Jump Around', 258, 1, 17, N'E. Schrody/L. Muggerud', 217835, 8715653, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Salutations', 258, 1, 17, N'E. Schrody/L. Dimant', 69120, 2767047, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Put Your Head Out', 258, 1, 17, N'E. Schrody/L. Freese/L. Muggerud', 182230, 7291473, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Top O'' The Morning To Ya', 258, 1, 17, N'E. Schrody/L. Dimant', 216633, 8667599, 0.99); INSERT INTO `Invoice` (`CustomerId`, `InvoiceDate`, `BillingAddress`, `BillingCity`, `BillingState`, `BillingCountry`, `BillingPostalCode`, `Total`) VALUES (48, '2013/8/2', N'Lijnbaansgracht 120bg', N'Amsterdam', N'VV', N'Netherlands', N'1016', 1.98);"
  + "select supplier_name,city from (select * from suppliers join addresses on suppliers.address_id=addresses.id) as suppliers where supplier_id>500 order by supplier_name asc,city desc; ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION; CREATE TABLE `Customer` ( `CustomerId` INT NOT NULL AUTO_INCREMENT, `FirstName` NVARCHAR(40) NOT NULL, `LastName` NVARCHAR(20) NOT NULL, `Company` NVARCHAR(80), `Address` NVARCHAR(70), `City` NVARCHAR(40), `State` NVARCHAR(40), `Country` NVARCHAR(40), `PostalCode` NVARCHAR(10), `Phone` NVARCHAR(24), `Fax` NVARCHAR(24), `Email` NVARCHAR(60) NOT NULL, `SupportRepId` INT, CONSTRAINT `PK_Customer` PRIMARY KEY  (`CustomerId`)); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Jump Around', 258, 1, 17, N'E. Schrody/L. Muggerud', 217835, 8715653, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Salutations', 258, 1, 17, N'E. Schrody/L. Dimant', 69120, 2767047, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Put Your Head Out', 258, 1, 17, N'E. Schrody/L. Freese/L. Muggerud', 182230, 7291473, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Top O'' The Morning To Ya', 258, 1, 17, N'E. Schrody/L. Dimant', 216633, 8667599, 0.99); INSERT INTO `Invoice` (`CustomerId`, `InvoiceDate`, `BillingAddress`, `BillingCity`, `BillingState`, `BillingCountry`, `BillingPostalCode`, `Total`) VALUES (48, '2013/8/2', N'Lijnbaansgracht 120bg', N'Amsterdam', N'VV', N'Netherlands', N'1016', 1.98);"
  + "select supplier_name,city from (select * from suppliers join addresses on suppliers.address_id=addresses.id) as suppliers where supplier_id>500 order by supplier_name asc,city desc; ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION; CREATE TABLE `Customer` ( `CustomerId` INT NOT NULL AUTO_INCREMENT, `FirstName` NVARCHAR(40) NOT NULL, `LastName` NVARCHAR(20) NOT NULL, `Company` NVARCHAR(80), `Address` NVARCHAR(70), `City` NVARCHAR(40), `State` NVARCHAR(40), `Country` NVARCHAR(40), `PostalCode` NVARCHAR(10), `Phone` NVARCHAR(24), `Fax` NVARCHAR(24), `Email` NVARCHAR(60) NOT NULL, `SupportRepId` INT, CONSTRAINT `PK_Customer` PRIMARY KEY  (`CustomerId`)); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Jump Around', 258, 1, 17, N'E. Schrody/L. Muggerud', 217835, 8715653, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Salutations', 258, 1, 17, N'E. Schrody/L. Dimant', 69120, 2767047, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Put Your Head Out', 258, 1, 17, N'E. Schrody/L. Freese/L. Muggerud', 182230, 7291473, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Top O'' The Morning To Ya', 258, 1, 17, N'E. Schrody/L. Dimant', 216633, 8667599, 0.99); INSERT INTO `Invoice` (`CustomerId`, `InvoiceDate`, `BillingAddress`, `BillingCity`, `BillingState`, `BillingCountry`, `BillingPostalCode`, `Total`) VALUES (48, '2013/8/2', N'Lijnbaansgracht 120bg', N'Amsterdam', N'VV', N'Netherlands', N'1016', 1.98);"
  + "select supplier_name,city from (select * from suppliers join addresses on suppliers.address_id=addresses.id) as suppliers where supplier_id>500 order by supplier_name asc,city desc; ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION; CREATE TABLE `Customer` ( `CustomerId` INT NOT NULL AUTO_INCREMENT, `FirstName` NVARCHAR(40) NOT NULL, `LastName` NVARCHAR(20) NOT NULL, `Company` NVARCHAR(80), `Address` NVARCHAR(70), `City` NVARCHAR(40), `State` NVARCHAR(40), `Country` NVARCHAR(40), `PostalCode` NVARCHAR(10), `Phone` NVARCHAR(24), `Fax` NVARCHAR(24), `Email` NVARCHAR(60) NOT NULL, `SupportRepId` INT, CONSTRAINT `PK_Customer` PRIMARY KEY  (`CustomerId`)); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Jump Around', 258, 1, 17, N'E. Schrody/L. Muggerud', 217835, 8715653, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Salutations', 258, 1, 17, N'E. Schrody/L. Dimant', 69120, 2767047, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Put Your Head Out', 258, 1, 17, N'E. Schrody/L. Freese/L. Muggerud', 182230, 7291473, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Top O'' The Morning To Ya', 258, 1, 17, N'E. Schrody/L. Dimant', 216633, 8667599, 0.99); INSERT INTO `Invoice` (`CustomerId`, `InvoiceDate`, `BillingAddress`, `BillingCity`, `BillingState`, `BillingCountry`, `BillingPostalCode`, `Total`) VALUES (48, '2013/8/2', N'Lijnbaansgracht 120bg', N'Amsterdam', N'VV', N'Netherlands', N'1016', 1.98);"
  + "select supplier_name,city from (select * from suppliers join addresses on suppliers.address_id=addresses.id) as suppliers where supplier_id>500 order by supplier_name asc,city desc; ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION; CREATE TABLE `Customer` ( `CustomerId` INT NOT NULL AUTO_INCREMENT, `FirstName` NVARCHAR(40) NOT NULL, `LastName` NVARCHAR(20) NOT NULL, `Company` NVARCHAR(80), `Address` NVARCHAR(70), `City` NVARCHAR(40), `State` NVARCHAR(40), `Country` NVARCHAR(40), `PostalCode` NVARCHAR(10), `Phone` NVARCHAR(24), `Fax` NVARCHAR(24), `Email` NVARCHAR(60) NOT NULL, `SupportRepId` INT, CONSTRAINT `PK_Customer` PRIMARY KEY  (`CustomerId`)); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Jump Around', 258, 1, 17, N'E. Schrody/L. Muggerud', 217835, 8715653, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Salutations', 258, 1, 17, N'E. Schrody/L. Dimant', 69120, 2767047, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Put Your Head Out', 258, 1, 17, N'E. Schrody/L. Freese/L. Muggerud', 182230, 7291473, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Top O'' The Morning To Ya', 258, 1, 17, N'E. Schrody/L. Dimant', 216633, 8667599, 0.99); INSERT INTO `Invoice` (`CustomerId`, `InvoiceDate`, `BillingAddress`, `BillingCity`, `BillingState`, `BillingCountry`, `BillingPostalCode`, `Total`) VALUES (48, '2013/8/2', N'Lijnbaansgracht 120bg', N'Amsterdam', N'VV', N'Netherlands', N'1016', 1.98);"
  + "select supplier_name,city from (select * from suppliers join addresses on suppliers.address_id=addresses.id) as suppliers where supplier_id>500 order by supplier_name asc,city desc; ALTER TABLE `Album` ADD CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `Artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION; CREATE TABLE `Customer` ( `CustomerId` INT NOT NULL AUTO_INCREMENT, `FirstName` NVARCHAR(40) NOT NULL, `LastName` NVARCHAR(20) NOT NULL, `Company` NVARCHAR(80), `Address` NVARCHAR(70), `City` NVARCHAR(40), `State` NVARCHAR(40), `Country` NVARCHAR(40), `PostalCode` NVARCHAR(10), `Phone` NVARCHAR(24), `Fax` NVARCHAR(24), `Email` NVARCHAR(60) NOT NULL, `SupportRepId` INT, CONSTRAINT `PK_Customer` PRIMARY KEY  (`CustomerId`)); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Jump Around', 258, 1, 17, N'E. Schrody/L. Muggerud', 217835, 8715653, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Salutations', 258, 1, 17, N'E. Schrody/L. Dimant', 69120, 2767047, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Put Your Head Out', 258, 1, 17, N'E. Schrody/L. Freese/L. Muggerud', 182230, 7291473, 0.99); INSERT INTO `Track` (`Name`, `AlbumId`, `MediaTypeId`, `GenreId`, `Composer`, `Milliseconds`, `Bytes`, `UnitPrice`) VALUES (N'Top O'' The Morning To Ya', 258, 1, 17, N'E. Schrody/L. Dimant', 216633, 8667599, 0.99); INSERT INTO `Invoice` (`CustomerId`, `InvoiceDate`, `BillingAddress`, `BillingCity`, `BillingState`, `BillingCountry`, `BillingPostalCode`, `Total`) VALUES (48, '2013/8/2', N'Lijnbaansgracht 120bg', N'Amsterdam', N'VV', N'Netherlands', N'1016', 1.98);"
, {
  language: "mysql",
});
```

The result is that Nearley branch is:

- 10 x slower in Firefox
- 4 x slower in Safari
- 10 x slower in Chrome

I have a small optimization in mind... will see whether this helps.

**Comment by nene** [comment]
I tried caching the creation of Nearley parser, but this had zero effect on performance :(

**Comment by nene** [comment]
Also checked that the performance degrades further as the size of SQL to be parsed increases. Like when I increased the size of SQL 4 times, the performance dropped from 9.8% to 6.8%.

But I'd say it's still acceptable. It's far from the old times when the formatter would just choke for that amount of SQL.

**Review by inferrinizzard — APPROVED** [review]

**Comment by nene** [comment]
Ran another performance test, this time with NodeJS using a local large SQL file (271KB). Here the difference was pretty staggering: The old version took just 450 ms, while the Nearley version took 20 seconds. That's about 40 x difference.

Looked into different phases of the formatter and everything else seemed to perform about the same as before, just that the parsing in old version took about 20ms (with tokenizing being the slowest part - about 200ms spent there), while with Nearley pretty much the entire 20 seconds was spent parsing.

It really shouldn't be that slow. The parsing should really happen in near linear time. 20 seconds to parse less than a megabyte of code is definitely very slow. I think I've done something wrong with how I've written the grammar, that makes the parsing process so slow.

**Comment by nene** [comment]
Found a [question about performance](https://github.com/kach/nearley/issues/312) in Nearly issues list, where three possible culprits for performance issues are listed:

1. not using a tokenizer
2. an ambiguos grammar
3. a right-recursive grammar

The first two can't really be a problem in our case. But it seems there are at least some right-recursive rules, like:

```
commaless_expression -> simple_expression | asterisk

simple_expression -> array_subscript | between_predicate | ...

between_predicate -> %BETWEEN commaless_expression %AND commaless_expression # <- right recursion here
```

**Comment by nene** [comment]
Discovered the culprit. Currently the grammar has this:

```
main -> statement (%DELIMITER statement):*

statement -> expressions_or_clauses
```

When I instead write this as:

```
main -> statement:*

statement -> expressions_or_clauses %DELIMITER
```

The processing of the same SQL that took 20 seconds will happen in just 1.3 seconds.

Will need to figure out how to rewrite this so that the delimiter would still be optional at the end. Too late today already...

**Comment by nene** [comment]
So, the major performance culprit is now eliminated. But the parser still gets slower as the input size increases:

- with 271KB file: old 450ms v/s new 1300ms - 2.8 x difference
- with 1.6MB file: old 1.6s v/s new 26s = 16 x difference

**Comment by nene** [comment]
Discovered another reason for performance problems. For the `main` rule we had essentially this:

```
main -> statement:* {% flatten %}
```

I assumed that this post-processor function gets called once, when all the statements have been matched. But instead it gets called at every step:

1. with 0 statements
2. with 1 statement
3. with 2 statements
4. ...

And as the `flatten()` loops through the whole array, we end up with O(n<sup>2</sup>) complexity.

I fixed (or at least alleviated) the problem in `main` rule. This brought the parsing time from 26 seconds to 8 seconds.

Similar problems are likely also present elsewhere where we currently use `rule:*` syntax and call `flatten()`. I'll see what can be done to improve this further.

**Comment by inferrinizzard** [comment]
Additionally, the README on nearley mentions how the earley algorithm it uses performs best when grammar rules are written left-recursively so I'd assume optimising for that would have additional gains in performance

**Comment by inferrinizzard** [comment]
Nice job with the bottlenecks with the performance testing, thanks for finding these

**Comment by nene** [comment]
I eliminated all uses of the `flatten()` function in the grammar file. This didn't bring any performance improvements, but at least it gets rid of one potential culprit, which is better to be avoided. It should mostly be possible to write all post-processors without the aid of this function.

We have several grammar rules that end with `rule:*`, like:

```
other_clause -> %RESERVED_COMMAND expression:*
```

While the post-processors of these rules are now relatively cheap, they still end up being called a lot of times, which is a possible cause for the performance loss. There's no such problem with rules like:

```
square_brackets -> "[" expression:* "]"
```

Here the final square bracket needs to be matched, for the rule to be considered fully matched and the post-processor to be called.

**Comment by nene** [comment]
I tested with a simplified grammar that only matches simple INSERT statements:

```
main -> statement:* %EOF

statement -> insert_clause values_clause %DELIMITER

insert_clause -> "INSERT INTO" identifier parenthesis

values_clause -> "VALUES" parenthesis
```

There's no partial-matching problem with this grammar, but it still took 6 seconds for it to format 1.6MB file full of insert statements.

But at least with this grammar the performance seems to be linear O(n). I went back and tested once more with the full grammar and this too seems to be performing linearly now. Though that might depend on the specific SQL used for testing. Some quick measurements:

- 2000 lines of SQL: 943ms
- 4000 lines of SQL: 2.15s (2.2x slower)
- 8000 lines of SQL: 3.84s (1.7x slower)
- 1600 lines of SQL: 7.48s (1.9x slower)

So at least it's a constant overhead and therefore more scalable. I guess the overhead is now purely the inherent overhead of using Nearley - one can always get more performance out of a manually written parser, but the question is whether the performance gains are worth the added complexity of writing it manually. Probably not.

With this I'm now finally satisfied with the performance.

**Pull request merged**
