### PR TITLE
Fix semicolon-on-separate-line bug

### PR DESCRIPTION
**Pull request by nene**
Add `WS.NO_NEWLINE` and `WS.MANDATORY_NEWLINE` to Layout engine. Also cover Layout class with tests.

Use these new features to:

1. Eliminate trailing newline before inserting semicolon.
2. Add non-removable newline at the end of a line-comment.

### CODE REVIEW

**Comment by inferrinizzard** [comment]
Looks good, can you also add tests for having the semicolon on a newline ?

**Comment by nene** [comment]
You mean a test for line-comment followed by semicolon?

There already exists one for that: https://github.com/sql-formatter-org/sql-formatter/blob/master/test/features/comments.ts#L59

**Comment by inferrinizzard** [comment]
No, I mean a standard statement followed by newline
ie.
```sql
SELECT *
FROM tbl
;
```

**Comment by nene** [comment]
So, you mean like: https://github.com/sql-formatter-org/sql-formatter/blob/master/test/options/newlineBeforeSemicolon.ts#L24

**Comment by nene** [comment]
I merged this in, as you approved this in general, and the only question is about an additional test.

Please do say if the test you were thinking of is still missing.

**Comment by inferrinizzard** [comment]
I meant with the new layout test file but I suppose the existing test is fine

**Comment by nene** [comment]
> I meant with the new layout test file but I suppose the existing test is fine

Well, for that there is a test for `MANDATORY_NEWLINE` followed by `NO_NEWLINE`. That's really the part that was needed to make it work. Doesn't really make much sense to test an actual semicolon in there - for Layout all plain strings (non-whitespace related) are the same.

**Pull request merged**
